// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: portalchain/poi/epoch_report.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EpochReport struct {
	Epoch            int64                                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Validator        string                                 `protobuf:"bytes,2,opt,name=validator,proto3" json:"validator,omitempty"`
	TasksProcessed   int64                                  `protobuf:"varint,3,opt,name=tasks_processed,json=tasksProcessed,proto3" json:"tasks_processed,omitempty"`
	WeightedTaskSum  int64                                  `protobuf:"varint,4,opt,name=weighted_task_sum,json=weightedTaskSum,proto3" json:"weighted_task_sum,omitempty"`
	AvgLatency       int64                                  `protobuf:"varint,5,opt,name=avg_latency,json=avgLatency,proto3" json:"avg_latency,omitempty"`
	Reliability      github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=reliability,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"reliability"`
	SamplingFailures int64                                  `protobuf:"varint,7,opt,name=sampling_failures,json=samplingFailures,proto3" json:"sampling_failures,omitempty"`
	Timestamp        int64                                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (m *EpochReport) Reset()         { *m = EpochReport{} }
func (m *EpochReport) String() string { return proto.CompactTextString(m) }
func (*EpochReport) ProtoMessage()    {}
func (*EpochReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_63213fb47a07f613, []int{0}
}
func (m *EpochReport) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EpochReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EpochReport.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EpochReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochReport.Merge(m, src)
}
func (m *EpochReport) XXX_Size() int {
	return m.Size()
}
func (m *EpochReport) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochReport.DiscardUnknown(m)
}

var xxx_messageInfo_EpochReport proto.InternalMessageInfo

func (m *EpochReport) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *EpochReport) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *EpochReport) GetTasksProcessed() int64 {
	if m != nil {
		return m.TasksProcessed
	}
	return 0
}

func (m *EpochReport) GetWeightedTaskSum() int64 {
	if m != nil {
		return m.WeightedTaskSum
	}
	return 0
}

func (m *EpochReport) GetAvgLatency() int64 {
	if m != nil {
		return m.AvgLatency
	}
	return 0
}

func (m *EpochReport) GetSamplingFailures() int64 {
	if m != nil {
		return m.SamplingFailures
	}
	return 0
}

func (m *EpochReport) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Reputation struct {
	Validator string                                 `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Value     github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=value,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"value"`
}

func (m *Reputation) Reset()         { *m = Reputation{} }
func (m *Reputation) String() string { return proto.CompactTextString(m) }
func (*Reputation) ProtoMessage()    {}
func (*Reputation) Descriptor() ([]byte, []int) {
	return fileDescriptor_63213fb47a07f613, []int{1}
}
func (m *Reputation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Reputation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Reputation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Reputation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reputation.Merge(m, src)
}
func (m *Reputation) XXX_Size() int {
	return m.Size()
}
func (m *Reputation) XXX_DiscardUnknown() {
	xxx_messageInfo_Reputation.DiscardUnknown(m)
}

var xxx_messageInfo_Reputation proto.InternalMessageInfo

func (m *Reputation) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func init() {
	proto.RegisterType((*EpochReport)(nil), "portalchain.poi.EpochReport")
	proto.RegisterType((*Reputation)(nil), "portalchain.poi.Reputation")
}

func init() {
	proto.RegisterFile("portalchain/poi/epoch_report.proto", fileDescriptor_63213fb47a07f613)
}

var fileDescriptor_63213fb47a07f613 = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4f, 0xf2, 0x30,
	0x1c, 0xc6, 0x37, 0x78, 0xe1, 0x95, 0x92, 0x88, 0x34, 0x24, 0x36, 0xc6, 0x0c, 0xc2, 0x41, 0x89,
	0xc6, 0x2d, 0xc6, 0x6f, 0x40, 0xd0, 0x93, 0x07, 0x32, 0x3d, 0x79, 0x59, 0xca, 0x56, 0xb7, 0x86,
	0x6e, 0x6d, 0xd6, 0x6e, 0xca, 0xb7, 0xf0, 0x63, 0x71, 0xe4, 0xe0, 0xc1, 0x78, 0x20, 0x06, 0xbe,
	0x88, 0x59, 0x07, 0x01, 0xbd, 0x79, 0xda, 0xf6, 0x7b, 0x9e, 0xe7, 0xbf, 0xf6, 0xc9, 0x1f, 0xf4,
	0x05, 0x4f, 0x15, 0x66, 0x7e, 0x84, 0x69, 0xe2, 0x08, 0x4e, 0x1d, 0x22, 0xb8, 0x1f, 0x79, 0x29,
	0x29, 0xb8, 0x2d, 0x52, 0xae, 0x38, 0x6c, 0xed, 0x79, 0x6c, 0xc1, 0xe9, 0x49, 0x27, 0xe4, 0x21,
	0xd7, 0x9a, 0x53, 0xbc, 0x95, 0xb6, 0xfe, 0x7b, 0x05, 0x34, 0x6f, 0x8b, 0xb4, 0xab, 0xc3, 0xb0,
	0x03, 0x6a, 0x7a, 0x18, 0x32, 0x7b, 0xe6, 0xa0, 0xea, 0x96, 0x1f, 0xf0, 0x14, 0x34, 0x72, 0xcc,
	0x68, 0x80, 0x15, 0x4f, 0x51, 0xa5, 0x67, 0x0e, 0x1a, 0xee, 0x0e, 0xc0, 0x73, 0xd0, 0x52, 0x58,
	0x4e, 0xa5, 0x27, 0x52, 0xee, 0x13, 0x29, 0x49, 0x80, 0xaa, 0x3a, 0x7d, 0xa8, 0xf1, 0x78, 0x4b,
	0xe1, 0x05, 0x68, 0xbf, 0x10, 0x1a, 0x46, 0x8a, 0x04, 0x5e, 0x21, 0x79, 0x32, 0x8b, 0xd1, 0x3f,
	0x6d, 0x6d, 0x6d, 0x85, 0x47, 0x2c, 0xa7, 0x0f, 0x59, 0x0c, 0xbb, 0xa0, 0x89, 0xf3, 0xd0, 0x63,
	0x58, 0x91, 0xc4, 0x9f, 0xa1, 0x9a, 0x76, 0x01, 0x9c, 0x87, 0xf7, 0x25, 0x81, 0x63, 0xd0, 0x4c,
	0x09, 0xa3, 0x78, 0x42, 0x19, 0x55, 0x33, 0x54, 0x2f, 0x4e, 0x35, 0xb4, 0xe7, 0xcb, 0xae, 0xf1,
	0xb9, 0xec, 0x9e, 0x85, 0x54, 0x45, 0xd9, 0xc4, 0xf6, 0x79, 0xec, 0xf8, 0x5c, 0xc6, 0x5c, 0x6e,
	0x1e, 0x57, 0x32, 0x98, 0x3a, 0x6a, 0x26, 0x88, 0xb4, 0x47, 0xc4, 0x77, 0xf7, 0x47, 0xc0, 0x4b,
	0xd0, 0x96, 0x38, 0x16, 0x8c, 0x26, 0xa1, 0xf7, 0x8c, 0x29, 0xcb, 0x52, 0x22, 0xd1, 0x7f, 0xfd,
	0xe3, 0xa3, 0xad, 0x70, 0xb7, 0xe1, 0x45, 0x25, 0x8a, 0xc6, 0x44, 0x2a, 0x1c, 0x0b, 0x74, 0xa0,
	0x4d, 0x3b, 0xd0, 0x17, 0x00, 0xb8, 0x44, 0x64, 0x0a, 0x2b, 0xca, 0x93, 0x9f, 0xf5, 0x99, 0xbf,
	0xeb, 0x1b, 0x81, 0x5a, 0x8e, 0x59, 0x46, 0xca, 0x62, 0xff, 0x7c, 0x85, 0x32, 0x3c, 0xbc, 0x9e,
	0xaf, 0x2c, 0x73, 0xb1, 0xb2, 0xcc, 0xaf, 0x95, 0x65, 0xbe, 0xad, 0x2d, 0x63, 0xb1, 0xb6, 0x8c,
	0x8f, 0xb5, 0x65, 0x3c, 0x1d, 0xef, 0x6f, 0xcb, 0xab, 0xde, 0x17, 0x9d, 0x9e, 0xd4, 0xf5, 0x0a,
	0xdc, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0x66, 0x8b, 0xb8, 0x11, 0x4f, 0x02, 0x00, 0x00,
}

func (m *EpochReport) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EpochReport) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EpochReport) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Timestamp != 0 {
		i = encodeVarintEpochReport(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x40
	}
	if m.SamplingFailures != 0 {
		i = encodeVarintEpochReport(dAtA, i, uint64(m.SamplingFailures))
		i--
		dAtA[i] = 0x38
	}
	{
		size := m.Reliability.Size()
		i -= size
		if _, err := m.Reliability.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEpochReport(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.AvgLatency != 0 {
		i = encodeVarintEpochReport(dAtA, i, uint64(m.AvgLatency))
		i--
		dAtA[i] = 0x28
	}
	if m.WeightedTaskSum != 0 {
		i = encodeVarintEpochReport(dAtA, i, uint64(m.WeightedTaskSum))
		i--
		dAtA[i] = 0x20
	}
	if m.TasksProcessed != 0 {
		i = encodeVarintEpochReport(dAtA, i, uint64(m.TasksProcessed))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintEpochReport(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0x12
	}
	if m.Epoch != 0 {
		i = encodeVarintEpochReport(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Reputation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Reputation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Reputation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Value.Size()
		i -= size
		if _, err := m.Value.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEpochReport(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintEpochReport(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEpochReport(dAtA []byte, offset int, v uint64) int {
	offset -= sovEpochReport(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EpochReport) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Epoch != 0 {
		n += 1 + sovEpochReport(uint64(m.Epoch))
	}
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovEpochReport(uint64(l))
	}
	if m.TasksProcessed != 0 {
		n += 1 + sovEpochReport(uint64(m.TasksProcessed))
	}
	if m.WeightedTaskSum != 0 {
		n += 1 + sovEpochReport(uint64(m.WeightedTaskSum))
	}
	if m.AvgLatency != 0 {
		n += 1 + sovEpochReport(uint64(m.AvgLatency))
	}
	l = m.Reliability.Size()
	n += 1 + l + sovEpochReport(uint64(l))
	if m.SamplingFailures != 0 {
		n += 1 + sovEpochReport(uint64(m.SamplingFailures))
	}
	if m.Timestamp != 0 {
		n += 1 + sovEpochReport(uint64(m.Timestamp))
	}
	return n
}

func (m *Reputation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovEpochReport(uint64(l))
	}
	l = m.Value.Size()
	n += 1 + l + sovEpochReport(uint64(l))
	return n
}

func sovEpochReport(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEpochReport(x uint64) (n int) {
	return sovEpochReport(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EpochReport) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEpochReport
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EpochReport: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EpochReport: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpochReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpochReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEpochReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEpochReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TasksProcessed", wireType)
			}
			m.TasksProcessed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpochReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TasksProcessed |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WeightedTaskSum", wireType)
			}
			m.WeightedTaskSum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpochReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WeightedTaskSum |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvgLatency", wireType)
			}
			m.AvgLatency = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpochReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AvgLatency |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reliability", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpochReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEpochReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEpochReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Reliability.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SamplingFailures", wireType)
			}
			m.SamplingFailures = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpochReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SamplingFailures |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpochReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEpochReport(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEpochReport
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Reputation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEpochReport
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Reputation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Reputation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpochReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEpochReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEpochReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpochReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEpochReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEpochReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Value.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEpochReport(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEpochReport
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEpochReport(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEpochReport
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEpochReport
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEpochReport
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEpochReport
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEpochReport
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEpochReport
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEpochReport        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEpochReport          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEpochReport = fmt.Errorf("proto: unexpected end of group")
)
