// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: portalchain/poi/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryEpochReportRequest struct {
	Epoch     int64  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Validator string `protobuf:"bytes,2,opt,name=validator,proto3" json:"validator,omitempty"`
}

func (m *QueryEpochReportRequest) Reset()         { *m = QueryEpochReportRequest{} }
func (m *QueryEpochReportRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEpochReportRequest) ProtoMessage()    {}
func (*QueryEpochReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e84944745539e3be, []int{0}
}
func (m *QueryEpochReportRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEpochReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEpochReportRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEpochReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEpochReportRequest.Merge(m, src)
}
func (m *QueryEpochReportRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEpochReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEpochReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEpochReportRequest proto.InternalMessageInfo

func (m *QueryEpochReportRequest) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *QueryEpochReportRequest) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

type QueryEpochReportResponse struct {
	Report EpochReport `protobuf:"bytes,1,opt,name=report,proto3" json:"report"`
}

func (m *QueryEpochReportResponse) Reset()         { *m = QueryEpochReportResponse{} }
func (m *QueryEpochReportResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEpochReportResponse) ProtoMessage()    {}
func (*QueryEpochReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e84944745539e3be, []int{1}
}
func (m *QueryEpochReportResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEpochReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEpochReportResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEpochReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEpochReportResponse.Merge(m, src)
}
func (m *QueryEpochReportResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEpochReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEpochReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEpochReportResponse proto.InternalMessageInfo

func (m *QueryEpochReportResponse) GetReport() EpochReport {
	if m != nil {
		return m.Report
	}
	return EpochReport{}
}

type QueryValidatorReputationRequest struct {
	Validator string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
}

func (m *QueryValidatorReputationRequest) Reset()         { *m = QueryValidatorReputationRequest{} }
func (m *QueryValidatorReputationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryValidatorReputationRequest) ProtoMessage()    {}
func (*QueryValidatorReputationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e84944745539e3be, []int{2}
}
func (m *QueryValidatorReputationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidatorReputationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidatorReputationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidatorReputationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidatorReputationRequest.Merge(m, src)
}
func (m *QueryValidatorReputationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidatorReputationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidatorReputationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidatorReputationRequest proto.InternalMessageInfo

func (m *QueryValidatorReputationRequest) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

type QueryValidatorReputationResponse struct {
	Reputation Reputation `protobuf:"bytes,1,opt,name=reputation,proto3" json:"reputation"`
}

func (m *QueryValidatorReputationResponse) Reset()         { *m = QueryValidatorReputationResponse{} }
func (m *QueryValidatorReputationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryValidatorReputationResponse) ProtoMessage()    {}
func (*QueryValidatorReputationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e84944745539e3be, []int{3}
}
func (m *QueryValidatorReputationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidatorReputationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidatorReputationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidatorReputationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidatorReputationResponse.Merge(m, src)
}
func (m *QueryValidatorReputationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidatorReputationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidatorReputationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidatorReputationResponse proto.InternalMessageInfo

func (m *QueryValidatorReputationResponse) GetReputation() Reputation {
	if m != nil {
		return m.Reputation
	}
	return Reputation{}
}

type QueryReportsByValidatorRequest struct {
	Validator  string             `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryReportsByValidatorRequest) Reset()         { *m = QueryReportsByValidatorRequest{} }
func (m *QueryReportsByValidatorRequest) String() string { return proto.CompactTextString(m) }
func (*QueryReportsByValidatorRequest) ProtoMessage()    {}
func (*QueryReportsByValidatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e84944745539e3be, []int{4}
}
func (m *QueryReportsByValidatorRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReportsByValidatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReportsByValidatorRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReportsByValidatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReportsByValidatorRequest.Merge(m, src)
}
func (m *QueryReportsByValidatorRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryReportsByValidatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReportsByValidatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReportsByValidatorRequest proto.InternalMessageInfo

func (m *QueryReportsByValidatorRequest) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *QueryReportsByValidatorRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryReportsByValidatorResponse struct {
	Reports    []EpochReport       `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryReportsByValidatorResponse) Reset()         { *m = QueryReportsByValidatorResponse{} }
func (m *QueryReportsByValidatorResponse) String() string { return proto.CompactTextString(m) }
func (*QueryReportsByValidatorResponse) ProtoMessage()    {}
func (*QueryReportsByValidatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e84944745539e3be, []int{5}
}
func (m *QueryReportsByValidatorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReportsByValidatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReportsByValidatorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReportsByValidatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReportsByValidatorResponse.Merge(m, src)
}
func (m *QueryReportsByValidatorResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryReportsByValidatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReportsByValidatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReportsByValidatorResponse proto.InternalMessageInfo

func (m *QueryReportsByValidatorResponse) GetReports() []EpochReport {
	if m != nil {
		return m.Reports
	}
	return nil
}

func (m *QueryReportsByValidatorResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryEpochReportRequest)(nil), "portalchain.poi.QueryEpochReportRequest")
	proto.RegisterType((*QueryEpochReportResponse)(nil), "portalchain.poi.QueryEpochReportResponse")
	proto.RegisterType((*QueryValidatorReputationRequest)(nil), "portalchain.poi.QueryValidatorReputationRequest")
	proto.RegisterType((*QueryValidatorReputationResponse)(nil), "portalchain.poi.QueryValidatorReputationResponse")
	proto.RegisterType((*QueryReportsByValidatorRequest)(nil), "portalchain.poi.QueryReportsByValidatorRequest")
	proto.RegisterType((*QueryReportsByValidatorResponse)(nil), "portalchain.poi.QueryReportsByValidatorResponse")
}

func init() { proto.RegisterFile("portalchain/poi/query.proto", fileDescriptor_e84944745539e3be) }

var fileDescriptor_e84944745539e3be = []byte{
	// 534 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xcf, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0x33, 0x8d, 0xad, 0xf4, 0xe5, 0x20, 0x8c, 0x85, 0x86, 0x6d, 0xd8, 0x86, 0x45, 0xda,
	0xd4, 0x1f, 0x3b, 0x4d, 0x7a, 0x13, 0x41, 0x0c, 0xa8, 0x27, 0x41, 0xf7, 0xd0, 0x83, 0x17, 0x99,
	0xc4, 0x61, 0xbb, 0x10, 0x77, 0xa6, 0x3b, 0x93, 0x62, 0x29, 0xbd, 0x78, 0xf0, 0x2c, 0x78, 0xf0,
	0x2f, 0x10, 0x04, 0xff, 0x91, 0x1e, 0x0b, 0x5e, 0x3c, 0x89, 0x24, 0xfe, 0x0f, 0x5e, 0x65, 0x67,
	0x26, 0xcd, 0x24, 0xd9, 0xc5, 0xf4, 0xb6, 0x3b, 0xef, 0x7d, 0xdf, 0xf7, 0x33, 0xef, 0xbd, 0x5d,
	0xd8, 0x12, 0x3c, 0x53, 0x74, 0xd0, 0x3f, 0xa2, 0x49, 0x4a, 0x04, 0x4f, 0xc8, 0xf1, 0x90, 0x65,
	0xa7, 0xa1, 0xc8, 0xb8, 0xe2, 0xf8, 0x96, 0x13, 0x0c, 0x05, 0x4f, 0xbc, 0x8d, 0x98, 0xc7, 0x5c,
	0xc7, 0x48, 0xfe, 0x64, 0xd2, 0xbc, 0x46, 0xcc, 0x79, 0x3c, 0x60, 0x84, 0x8a, 0x84, 0xd0, 0x34,
	0xe5, 0x8a, 0xaa, 0x84, 0xa7, 0xd2, 0x46, 0xef, 0xf6, 0xb9, 0x7c, 0xc7, 0x25, 0xe9, 0x51, 0xc9,
	0x4c, 0x75, 0x72, 0xd2, 0xee, 0x31, 0x45, 0xdb, 0x44, 0xd0, 0x38, 0x49, 0x75, 0xb2, 0xcd, 0x0d,
	0xe6, 0x69, 0x98, 0xe0, 0xfd, 0xa3, 0x37, 0x19, 0xcb, 0xcf, 0x4d, 0x4e, 0xf0, 0x02, 0x36, 0x5f,
	0xe5, 0x55, 0x9e, 0xe6, 0xa1, 0x48, 0x47, 0x22, 0x76, 0x3c, 0x64, 0x52, 0xe1, 0x0d, 0x58, 0xd5,
	0x82, 0x3a, 0x6a, 0xa2, 0x56, 0x35, 0x32, 0x2f, 0xb8, 0x01, 0xeb, 0x27, 0x74, 0x90, 0xbc, 0xa5,
	0x8a, 0x67, 0xf5, 0x95, 0x26, 0x6a, 0xad, 0x47, 0xd3, 0x83, 0xe0, 0x10, 0xea, 0x8b, 0xe5, 0xa4,
	0xe0, 0xa9, 0x64, 0xf8, 0x21, 0xac, 0x19, 0x6b, 0x5d, 0xb0, 0xd6, 0x69, 0x84, 0x73, 0x0d, 0x09,
	0x1d, 0x55, 0xf7, 0xc6, 0xc5, 0xaf, 0xed, 0x4a, 0x64, 0x15, 0xc1, 0x63, 0xd8, 0xd6, 0x75, 0x0f,
	0x27, 0x4e, 0x11, 0x13, 0x43, 0xd3, 0x99, 0x09, 0xee, 0x0c, 0x18, 0x9a, 0x07, 0x63, 0xd0, 0x2c,
	0x2f, 0x60, 0x01, 0x9f, 0x00, 0x64, 0x57, 0xa7, 0x16, 0x72, 0x6b, 0x01, 0x72, 0x2a, 0xb4, 0x8c,
	0x8e, 0x28, 0xf8, 0x88, 0xc0, 0xd7, 0x3e, 0xe6, 0x16, 0xb2, 0xeb, 0x1a, 0x2e, 0xc1, 0x89, 0x9f,
	0x01, 0x4c, 0xe7, 0xa8, 0xfb, 0x5b, 0xeb, 0xec, 0x84, 0x66, 0xe8, 0x61, 0x3e, 0xf4, 0xd0, 0xac,
	0x94, 0x1d, 0x7a, 0xf8, 0x92, 0xc6, 0xcc, 0x56, 0x8e, 0x1c, 0x65, 0xf0, 0x0d, 0xd9, 0x8e, 0x15,
	0x81, 0xd8, 0xfb, 0x3e, 0x82, 0x9b, 0xa6, 0xbd, 0xb2, 0x8e, 0x9a, 0xd5, 0x25, 0x27, 0x32, 0x91,
	0xe0, 0xe7, 0x05, 0xa4, 0xbb, 0xff, 0x25, 0x35, 0xd6, 0x2e, 0x6a, 0xe7, 0x6f, 0x15, 0x56, 0x35,
	0x2a, 0xfe, 0x82, 0xa0, 0xe6, 0x38, 0xe2, 0xd6, 0x02, 0x4f, 0xc9, 0xae, 0x7a, 0x7b, 0x4b, 0x64,
	0x1a, 0xeb, 0xe0, 0xe0, 0xc3, 0x8f, 0x3f, 0x9f, 0x57, 0x1e, 0xe0, 0x7b, 0x64, 0xfe, 0xf3, 0x30,
	0x37, 0x23, 0x67, 0x7a, 0xd1, 0xcf, 0xc9, 0xd9, 0xd5, 0x54, 0xce, 0xf1, 0x77, 0x04, 0xb7, 0x0b,
	0x56, 0x07, 0xef, 0x17, 0xfb, 0x96, 0xaf, 0xa9, 0xd7, 0xbe, 0x86, 0xc2, 0x12, 0x13, 0x4d, 0xbc,
	0x87, 0x77, 0x8b, 0x88, 0x6d, 0xf2, 0x0c, 0xed, 0x57, 0x04, 0x78, 0x71, 0xee, 0x98, 0x14, 0x5b,
	0x97, 0xae, 0xaa, 0xb7, 0xbf, 0xbc, 0xc0, 0xa2, 0xde, 0xd7, 0xa8, 0x3b, 0xf8, 0x4e, 0x49, 0x73,
	0xa5, 0xcb, 0xd9, 0x6d, 0x5f, 0x8c, 0x7c, 0x74, 0x39, 0xf2, 0xd1, 0xef, 0x91, 0x8f, 0x3e, 0x8d,
	0xfd, 0xca, 0xe5, 0xd8, 0xaf, 0xfc, 0x1c, 0xfb, 0x95, 0xd7, 0x9b, 0xae, 0xfc, 0xbd, 0x2e, 0xa0,
	0x4e, 0x05, 0x93, 0xbd, 0x35, 0xfd, 0xdb, 0x3a, 0xf8, 0x17, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x4c,
	0x8e, 0x83, 0x6a, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	EpochReport(ctx context.Context, in *QueryEpochReportRequest, opts ...grpc.CallOption) (*QueryEpochReportResponse, error)
	ValidatorReputation(ctx context.Context, in *QueryValidatorReputationRequest, opts ...grpc.CallOption) (*QueryValidatorReputationResponse, error)
	ReportsByValidator(ctx context.Context, in *QueryReportsByValidatorRequest, opts ...grpc.CallOption) (*QueryReportsByValidatorResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) EpochReport(ctx context.Context, in *QueryEpochReportRequest, opts ...grpc.CallOption) (*QueryEpochReportResponse, error) {
	out := new(QueryEpochReportResponse)
	err := c.cc.Invoke(ctx, "/portalchain.poi.Query/EpochReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ValidatorReputation(ctx context.Context, in *QueryValidatorReputationRequest, opts ...grpc.CallOption) (*QueryValidatorReputationResponse, error) {
	out := new(QueryValidatorReputationResponse)
	err := c.cc.Invoke(ctx, "/portalchain.poi.Query/ValidatorReputation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ReportsByValidator(ctx context.Context, in *QueryReportsByValidatorRequest, opts ...grpc.CallOption) (*QueryReportsByValidatorResponse, error) {
	out := new(QueryReportsByValidatorResponse)
	err := c.cc.Invoke(ctx, "/portalchain.poi.Query/ReportsByValidator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	EpochReport(context.Context, *QueryEpochReportRequest) (*QueryEpochReportResponse, error)
	ValidatorReputation(context.Context, *QueryValidatorReputationRequest) (*QueryValidatorReputationResponse, error)
	ReportsByValidator(context.Context, *QueryReportsByValidatorRequest) (*QueryReportsByValidatorResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) EpochReport(ctx context.Context, req *QueryEpochReportRequest) (*QueryEpochReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EpochReport not implemented")
}
func (*UnimplementedQueryServer) ValidatorReputation(ctx context.Context, req *QueryValidatorReputationRequest) (*QueryValidatorReputationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidatorReputation not implemented")
}
func (*UnimplementedQueryServer) ReportsByValidator(ctx context.Context, req *QueryReportsByValidatorRequest) (*QueryReportsByValidatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportsByValidator not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_EpochReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEpochReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EpochReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portalchain.poi.Query/EpochReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EpochReport(ctx, req.(*QueryEpochReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ValidatorReputation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryValidatorReputationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ValidatorReputation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portalchain.poi.Query/ValidatorReputation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ValidatorReputation(ctx, req.(*QueryValidatorReputationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ReportsByValidator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReportsByValidatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ReportsByValidator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portalchain.poi.Query/ReportsByValidator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ReportsByValidator(ctx, req.(*QueryReportsByValidatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "portalchain.poi.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EpochReport",
			Handler:    _Query_EpochReport_Handler,
		},
		{
			MethodName: "ValidatorReputation",
			Handler:    _Query_ValidatorReputation_Handler,
		},
		{
			MethodName: "ReportsByValidator",
			Handler:    _Query_ReportsByValidator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portalchain/poi/query.proto",
}

func (m *QueryEpochReportRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEpochReportRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEpochReportRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0x12
	}
	if m.Epoch != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryEpochReportResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEpochReportResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEpochReportResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Report.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryValidatorReputationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidatorReputationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidatorReputationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryValidatorReputationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidatorReputationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidatorReputationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Reputation.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryReportsByValidatorRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReportsByValidatorRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReportsByValidatorRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryReportsByValidatorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReportsByValidatorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReportsByValidatorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Reports) > 0 {
		for iNdEx := len(m.Reports) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Reports[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryEpochReportRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Epoch != 0 {
		n += 1 + sovQuery(uint64(m.Epoch))
	}
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEpochReportResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Report.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryValidatorReputationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryValidatorReputationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Reputation.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryReportsByValidatorRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryReportsByValidatorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Reports) > 0 {
		for _, e := range m.Reports {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryEpochReportRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEpochReportRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEpochReportRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEpochReportResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEpochReportResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEpochReportResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Report", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Report.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidatorReputationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidatorReputationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidatorReputationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidatorReputationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidatorReputationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidatorReputationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reputation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Reputation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReportsByValidatorRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReportsByValidatorRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReportsByValidatorRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReportsByValidatorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReportsByValidatorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReportsByValidatorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reports", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reports = append(m.Reports, EpochReport{})
			if err := m.Reports[len(m.Reports)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
