// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: portalchain/poi/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSubmitEpochReport struct {
	Epoch            int64                                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Validator        string                                 `protobuf:"bytes,2,opt,name=validator,proto3" json:"validator,omitempty"`
	TasksProcessed   int64                                  `protobuf:"varint,3,opt,name=tasks_processed,json=tasksProcessed,proto3" json:"tasks_processed,omitempty"`
	WeightedTaskSum  int64                                  `protobuf:"varint,4,opt,name=weighted_task_sum,json=weightedTaskSum,proto3" json:"weighted_task_sum,omitempty"`
	AvgLatency       int64                                  `protobuf:"varint,5,opt,name=avg_latency,json=avgLatency,proto3" json:"avg_latency,omitempty"`
	Reliability      github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=reliability,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"reliability"`
	SamplingFailures int64                                  `protobuf:"varint,7,opt,name=sampling_failures,json=samplingFailures,proto3" json:"sampling_failures,omitempty"`
	Timestamp        int64                                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TaskType         string                                 `protobuf:"bytes,9,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
}

func (m *MsgSubmitEpochReport) Reset()         { *m = MsgSubmitEpochReport{} }
func (m *MsgSubmitEpochReport) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitEpochReport) ProtoMessage()    {}
func (*MsgSubmitEpochReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1ad7c8866442f72, []int{0}
}
func (m *MsgSubmitEpochReport) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitEpochReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitEpochReport.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitEpochReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitEpochReport.Merge(m, src)
}
func (m *MsgSubmitEpochReport) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitEpochReport) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitEpochReport.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitEpochReport proto.InternalMessageInfo

func (m *MsgSubmitEpochReport) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *MsgSubmitEpochReport) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *MsgSubmitEpochReport) GetTasksProcessed() int64 {
	if m != nil {
		return m.TasksProcessed
	}
	return 0
}

func (m *MsgSubmitEpochReport) GetWeightedTaskSum() int64 {
	if m != nil {
		return m.WeightedTaskSum
	}
	return 0
}

func (m *MsgSubmitEpochReport) GetAvgLatency() int64 {
	if m != nil {
		return m.AvgLatency
	}
	return 0
}

func (m *MsgSubmitEpochReport) GetSamplingFailures() int64 {
	if m != nil {
		return m.SamplingFailures
	}
	return 0
}

func (m *MsgSubmitEpochReport) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MsgSubmitEpochReport) GetTaskType() string {
	if m != nil {
		return m.TaskType
	}
	return ""
}

type MsgSubmitEpochReportResponse struct {
}

func (m *MsgSubmitEpochReportResponse) Reset()         { *m = MsgSubmitEpochReportResponse{} }
func (m *MsgSubmitEpochReportResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitEpochReportResponse) ProtoMessage()    {}
func (*MsgSubmitEpochReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1ad7c8866442f72, []int{1}
}
func (m *MsgSubmitEpochReportResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitEpochReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitEpochReportResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitEpochReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitEpochReportResponse.Merge(m, src)
}
func (m *MsgSubmitEpochReportResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitEpochReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitEpochReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitEpochReportResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSubmitEpochReport)(nil), "portalchain.poi.MsgSubmitEpochReport")
	proto.RegisterType((*MsgSubmitEpochReportResponse)(nil), "portalchain.poi.MsgSubmitEpochReportResponse")
}

func init() { proto.RegisterFile("portalchain/poi/tx.proto", fileDescriptor_e1ad7c8866442f72) }

var fileDescriptor_e1ad7c8866442f72 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0x4d, 0xba, 0xb4, 0x34, 0xae, 0xc4, 0xb2, 0xd6, 0x4a, 0x58, 0xa5, 0xca, 0x56, 0x95, 0x80,
	0x0a, 0xd4, 0x44, 0xc0, 0x1f, 0x54, 0xc0, 0x89, 0x4a, 0x55, 0xda, 0x13, 0x97, 0xc8, 0x49, 0x8c,
	0x63, 0x6d, 0x1c, 0x5b, 0x19, 0x67, 0x69, 0xfe, 0x82, 0xcf, 0xea, 0xb1, 0x47, 0xc4, 0xa1, 0x42,
	0xbb, 0x7f, 0xc1, 0x09, 0xd9, 0x69, 0xb4, 0x2b, 0xd8, 0x03, 0x27, 0x7b, 0xde, 0x7b, 0x33, 0x63,
	0xbf, 0x19, 0x44, 0xb4, 0x6a, 0x0c, 0xad, 0xf2, 0x92, 0x8a, 0x3a, 0xd6, 0x4a, 0xc4, 0xe6, 0x26,
	0xd2, 0x8d, 0x32, 0x0a, 0x8f, 0x37, 0x98, 0x48, 0x2b, 0x71, 0x38, 0xe5, 0x8a, 0x2b, 0xc7, 0xc5,
	0xf6, 0xd6, 0xcb, 0x4e, 0x7e, 0xef, 0xa0, 0xe9, 0x05, 0xf0, 0xab, 0x36, 0x93, 0xc2, 0x7c, 0xd4,
	0x2a, 0x2f, 0x13, 0x66, 0x33, 0xf1, 0x14, 0xed, 0x32, 0x1b, 0x12, 0xff, 0xd8, 0x3f, 0x1d, 0x25,
	0x7d, 0x80, 0x8f, 0x50, 0xb0, 0xa0, 0x95, 0x28, 0xa8, 0x51, 0x0d, 0xd9, 0x39, 0xf6, 0x4f, 0x83,
	0x64, 0x0d, 0xe0, 0x57, 0x68, 0x6c, 0x28, 0xcc, 0x21, 0xd5, 0x8d, 0xca, 0x19, 0x00, 0x2b, 0xc8,
	0xc8, 0x65, 0x3f, 0x71, 0xf0, 0xe5, 0x80, 0xe2, 0xd7, 0x68, 0xf2, 0x8d, 0x09, 0x5e, 0x1a, 0x56,
	0xa4, 0x96, 0x4a, 0xa1, 0x95, 0xe4, 0x91, 0x93, 0x8e, 0x07, 0xe2, 0x9a, 0xc2, 0xfc, 0xaa, 0x95,
	0x78, 0x86, 0x0e, 0xe8, 0x82, 0xa7, 0x15, 0x35, 0xac, 0xce, 0x3b, 0xb2, 0xeb, 0x54, 0x88, 0x2e,
	0xf8, 0xe7, 0x1e, 0xc1, 0x97, 0xe8, 0xa0, 0x61, 0x95, 0xa0, 0x99, 0xa8, 0x84, 0xe9, 0xc8, 0x9e,
	0x7d, 0xd5, 0x79, 0x74, 0x7b, 0x3f, 0xf3, 0x7e, 0xde, 0xcf, 0x5e, 0x72, 0x61, 0xca, 0x36, 0x8b,
	0x72, 0x25, 0xe3, 0x5c, 0x81, 0x54, 0xf0, 0x70, 0x9c, 0x41, 0x31, 0x8f, 0x4d, 0xa7, 0x19, 0x44,
	0x1f, 0x58, 0x9e, 0x6c, 0x96, 0xc0, 0x6f, 0xd0, 0x04, 0xa8, 0xd4, 0x95, 0xa8, 0x79, 0xfa, 0x95,
	0x8a, 0xaa, 0x6d, 0x18, 0x90, 0xc7, 0xae, 0xf1, 0xd3, 0x81, 0xf8, 0xf4, 0x80, 0x5b, 0x4b, 0x8c,
	0x90, 0x0c, 0x0c, 0x95, 0x9a, 0xec, 0x3b, 0xd1, 0x1a, 0xc0, 0xcf, 0x51, 0xe0, 0x3e, 0x68, 0x3b,
	0x91, 0xc0, 0x19, 0xb6, 0x6f, 0x81, 0xeb, 0x4e, 0xb3, 0x93, 0x10, 0x1d, 0x6d, 0xf3, 0x3e, 0x61,
	0xa0, 0x55, 0x0d, 0xec, 0x9d, 0x46, 0xa3, 0x0b, 0xe0, 0x58, 0xa0, 0xc9, 0xbf, 0xf3, 0x79, 0x11,
	0xfd, 0x35, 0xe0, 0x68, 0x5b, 0xa9, 0xc3, 0xb3, 0xff, 0x92, 0x0d, 0x1d, 0xcf, 0xdf, 0xde, 0x2e,
	0x43, 0xff, 0x6e, 0x19, 0xfa, 0xbf, 0x96, 0xa1, 0xff, 0x7d, 0x15, 0x7a, 0x77, 0xab, 0xd0, 0xfb,
	0xb1, 0x0a, 0xbd, 0x2f, 0xcf, 0x36, 0x37, 0xed, 0xa6, 0xdf, 0x35, 0xeb, 0x5e, 0xb6, 0xe7, 0x16,
	0xe9, 0xfd, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x60, 0x98, 0xb3, 0x03, 0x8b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SubmitEpochReport(ctx context.Context, in *MsgSubmitEpochReport, opts ...grpc.CallOption) (*MsgSubmitEpochReportResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitEpochReport(ctx context.Context, in *MsgSubmitEpochReport, opts ...grpc.CallOption) (*MsgSubmitEpochReportResponse, error) {
	out := new(MsgSubmitEpochReportResponse)
	err := c.cc.Invoke(ctx, "/portalchain.poi.Msg/SubmitEpochReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SubmitEpochReport(context.Context, *MsgSubmitEpochReport) (*MsgSubmitEpochReportResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitEpochReport(ctx context.Context, req *MsgSubmitEpochReport) (*MsgSubmitEpochReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitEpochReport not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitEpochReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitEpochReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitEpochReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portalchain.poi.Msg/SubmitEpochReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitEpochReport(ctx, req.(*MsgSubmitEpochReport))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "portalchain.poi.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitEpochReport",
			Handler:    _Msg_SubmitEpochReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portalchain/poi/tx.proto",
}

func (m *MsgSubmitEpochReport) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitEpochReport) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitEpochReport) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TaskType) > 0 {
		i -= len(m.TaskType)
		copy(dAtA[i:], m.TaskType)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TaskType)))
		i--
		dAtA[i] = 0x4a
	}
	if m.Timestamp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x40
	}
	if m.SamplingFailures != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SamplingFailures))
		i--
		dAtA[i] = 0x38
	}
	{
		size := m.Reliability.Size()
		i -= size
		if _, err := m.Reliability.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.AvgLatency != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.AvgLatency))
		i--
		dAtA[i] = 0x28
	}
	if m.WeightedTaskSum != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.WeightedTaskSum))
		i--
		dAtA[i] = 0x20
	}
	if m.TasksProcessed != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TasksProcessed))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0x12
	}
	if m.Epoch != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitEpochReportResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitEpochReportResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitEpochReportResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSubmitEpochReport) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Epoch != 0 {
		n += 1 + sovTx(uint64(m.Epoch))
	}
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TasksProcessed != 0 {
		n += 1 + sovTx(uint64(m.TasksProcessed))
	}
	if m.WeightedTaskSum != 0 {
		n += 1 + sovTx(uint64(m.WeightedTaskSum))
	}
	if m.AvgLatency != 0 {
		n += 1 + sovTx(uint64(m.AvgLatency))
	}
	l = m.Reliability.Size()
	n += 1 + l + sovTx(uint64(l))
	if m.SamplingFailures != 0 {
		n += 1 + sovTx(uint64(m.SamplingFailures))
	}
	if m.Timestamp != 0 {
		n += 1 + sovTx(uint64(m.Timestamp))
	}
	l = len(m.TaskType)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitEpochReportResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSubmitEpochReport) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitEpochReport: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitEpochReport: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TasksProcessed", wireType)
			}
			m.TasksProcessed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TasksProcessed |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WeightedTaskSum", wireType)
			}
			m.WeightedTaskSum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WeightedTaskSum |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvgLatency", wireType)
			}
			m.AvgLatency = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AvgLatency |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reliability", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Reliability.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SamplingFailures", wireType)
			}
			m.SamplingFailures = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SamplingFailures |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitEpochReportResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitEpochReportResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitEpochReportResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
