version: 1
accounts:
  - name: alice
    coins: ["200000000portal"]
  - name: bob
    coins: ["100000000portal"]
client:
  openapi:
    path: docs/static/openapi.yml
validators:
  - name: alice
    bonded: "100000000portal"
genesis:
  app_state:
    mint:
      params:
        mint_denom: "portal"
        inflation_rate_change: "0.000000000000000000"
        inflation_max: "0.010000000000000000"
        inflation_min: "0.010000000000000000"
        blocks_per_year: "6311520"
    distribution:
      params:
        community_tax: "0.100000000000000000"
        base_proposer_reward: "0.010000000000000000"
        bonus_proposer_reward: "0.040000000000000000"
        withdraw_addr_enabled: true
    staking:
      params:
        unbonding_time: "1814400s"
        max_validators: 20
        max_entries: 7
        historical_entries: 10000
        bond_denom: "portal"
    slashing:
      params:
        signed_blocks_window: "10000"
        min_signed_per_window: "0.050000000000000000"
        downtime_jail_duration: "600s"
        slash_fraction_double_sign: "0.010000000000000000"
        slash_fraction_downtime: "0.000100000000000000"
