// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: portalchain/tasks/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryListTasksRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryListTasksRequest) Reset()         { *m = QueryListTasksRequest{} }
func (m *QueryListTasksRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListTasksRequest) ProtoMessage()    {}
func (*QueryListTasksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b54033f3f1f7419c, []int{0}
}
func (m *QueryListTasksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryListTasksRequest.Unmarshal(m, b)
}
func (m *QueryListTasksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryListTasksRequest.Marshal(b, m, deterministic)
}
func (m *QueryListTasksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListTasksRequest.Merge(m, src)
}
func (m *QueryListTasksRequest) XXX_Size() int {
	return xxx_messageInfo_QueryListTasksRequest.Size(m)
}
func (m *QueryListTasksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListTasksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListTasksRequest proto.InternalMessageInfo

type QueryListTasksResponse struct {
	TasksJson            string   `protobuf:"bytes,1,opt,name=tasks_json,json=tasksJson,proto3" json:"tasks_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryListTasksResponse) Reset()         { *m = QueryListTasksResponse{} }
func (m *QueryListTasksResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListTasksResponse) ProtoMessage()    {}
func (*QueryListTasksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b54033f3f1f7419c, []int{1}
}
func (m *QueryListTasksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryListTasksResponse.Unmarshal(m, b)
}
func (m *QueryListTasksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryListTasksResponse.Marshal(b, m, deterministic)
}
func (m *QueryListTasksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListTasksResponse.Merge(m, src)
}
func (m *QueryListTasksResponse) XXX_Size() int {
	return xxx_messageInfo_QueryListTasksResponse.Size(m)
}
func (m *QueryListTasksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListTasksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListTasksResponse proto.InternalMessageInfo

func (m *QueryListTasksResponse) GetTasksJson() string {
	if m != nil {
		return m.TasksJson
	}
	return ""
}

type QueryGetTaskRequest struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryGetTaskRequest) Reset()         { *m = QueryGetTaskRequest{} }
func (m *QueryGetTaskRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetTaskRequest) ProtoMessage()    {}
func (*QueryGetTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b54033f3f1f7419c, []int{2}
}
func (m *QueryGetTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGetTaskRequest.Unmarshal(m, b)
}
func (m *QueryGetTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGetTaskRequest.Marshal(b, m, deterministic)
}
func (m *QueryGetTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTaskRequest.Merge(m, src)
}
func (m *QueryGetTaskRequest) XXX_Size() int {
	return xxx_messageInfo_QueryGetTaskRequest.Size(m)
}
func (m *QueryGetTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTaskRequest proto.InternalMessageInfo

func (m *QueryGetTaskRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

type QueryGetTaskResponse struct {
	TaskJson             string   `protobuf:"bytes,1,opt,name=task_json,json=taskJson,proto3" json:"task_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryGetTaskResponse) Reset()         { *m = QueryGetTaskResponse{} }
func (m *QueryGetTaskResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetTaskResponse) ProtoMessage()    {}
func (*QueryGetTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b54033f3f1f7419c, []int{3}
}
func (m *QueryGetTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGetTaskResponse.Unmarshal(m, b)
}
func (m *QueryGetTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGetTaskResponse.Marshal(b, m, deterministic)
}
func (m *QueryGetTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTaskResponse.Merge(m, src)
}
func (m *QueryGetTaskResponse) XXX_Size() int {
	return xxx_messageInfo_QueryGetTaskResponse.Size(m)
}
func (m *QueryGetTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTaskResponse proto.InternalMessageInfo

func (m *QueryGetTaskResponse) GetTaskJson() string {
	if m != nil {
		return m.TaskJson
	}
	return ""
}

type QueryAgentTasksRequest struct {
	Agent                string   `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAgentTasksRequest) Reset()         { *m = QueryAgentTasksRequest{} }
func (m *QueryAgentTasksRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAgentTasksRequest) ProtoMessage()    {}
func (*QueryAgentTasksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b54033f3f1f7419c, []int{4}
}
func (m *QueryAgentTasksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAgentTasksRequest.Unmarshal(m, b)
}
func (m *QueryAgentTasksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAgentTasksRequest.Marshal(b, m, deterministic)
}
func (m *QueryAgentTasksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAgentTasksRequest.Merge(m, src)
}
func (m *QueryAgentTasksRequest) XXX_Size() int {
	return xxx_messageInfo_QueryAgentTasksRequest.Size(m)
}
func (m *QueryAgentTasksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAgentTasksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAgentTasksRequest proto.InternalMessageInfo

func (m *QueryAgentTasksRequest) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

type QueryAgentTasksResponse struct {
	TasksJson            string   `protobuf:"bytes,1,opt,name=tasks_json,json=tasksJson,proto3" json:"tasks_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAgentTasksResponse) Reset()         { *m = QueryAgentTasksResponse{} }
func (m *QueryAgentTasksResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAgentTasksResponse) ProtoMessage()    {}
func (*QueryAgentTasksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b54033f3f1f7419c, []int{5}
}
func (m *QueryAgentTasksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAgentTasksResponse.Unmarshal(m, b)
}
func (m *QueryAgentTasksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAgentTasksResponse.Marshal(b, m, deterministic)
}
func (m *QueryAgentTasksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAgentTasksResponse.Merge(m, src)
}
func (m *QueryAgentTasksResponse) XXX_Size() int {
	return xxx_messageInfo_QueryAgentTasksResponse.Size(m)
}
func (m *QueryAgentTasksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAgentTasksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAgentTasksResponse proto.InternalMessageInfo

func (m *QueryAgentTasksResponse) GetTasksJson() string {
	if m != nil {
		return m.TasksJson
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryListTasksRequest)(nil), "portalchain.tasks.QueryListTasksRequest")
	proto.RegisterType((*QueryListTasksResponse)(nil), "portalchain.tasks.QueryListTasksResponse")
	proto.RegisterType((*QueryGetTaskRequest)(nil), "portalchain.tasks.QueryGetTaskRequest")
	proto.RegisterType((*QueryGetTaskResponse)(nil), "portalchain.tasks.QueryGetTaskResponse")
	proto.RegisterType((*QueryAgentTasksRequest)(nil), "portalchain.tasks.QueryAgentTasksRequest")
	proto.RegisterType((*QueryAgentTasksResponse)(nil), "portalchain.tasks.QueryAgentTasksResponse")
}

func init() { proto.RegisterFile("portalchain/tasks/query.proto", fileDescriptor_b54033f3f1f7419c) }

var fileDescriptor_b54033f3f1f7419c = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x4e, 0x02, 0x31,
	0x10, 0xcd, 0x6a, 0x00, 0x99, 0x9b, 0x15, 0x5d, 0x59, 0x40, 0x49, 0x63, 0x14, 0x3d, 0x6c, 0x13,
	0x39, 0xe8, 0x55, 0x2f, 0x46, 0xe3, 0x45, 0xe2, 0xc9, 0x0b, 0xa9, 0xd2, 0xac, 0xab, 0xa4, 0x5d,
	0x68, 0x49, 0x24, 0x84, 0x44, 0xbd, 0x7b, 0xf2, 0xee, 0x4f, 0xf9, 0x0b, 0x7e, 0x88, 0xe9, 0x6c,
	0xa3, 0xe0, 0x42, 0xe4, 0xb4, 0xdb, 0x99, 0x37, 0xf3, 0x5e, 0xdf, 0x2b, 0xd4, 0x12, 0xd5, 0x37,
	0xbc, 0x7b, 0x77, 0xcf, 0x63, 0xc9, 0x0c, 0xd7, 0x8f, 0x9a, 0xf5, 0x06, 0xa2, 0x3f, 0x0c, 0x93,
	0xbe, 0x32, 0x8a, 0xac, 0x4e, 0xb4, 0x43, 0x6c, 0x07, 0xa5, 0x48, 0x45, 0x0a, 0xbb, 0xcc, 0xfe,
	0xa5, 0xc0, 0xa0, 0x1a, 0x29, 0x15, 0x75, 0x05, 0xe3, 0x49, 0xcc, 0xb8, 0x94, 0xca, 0x70, 0x13,
	0x2b, 0xa9, 0xd3, 0x2e, 0xf5, 0x61, 0xfd, 0xca, 0x6e, 0xbd, 0x8c, 0xb5, 0xb9, 0xb6, 0x5b, 0x5a,
	0xa2, 0x37, 0x10, 0xda, 0xd0, 0x23, 0xd8, 0xf8, 0xdb, 0xd0, 0x89, 0x92, 0x5a, 0x90, 0x1a, 0x00,
	0xf2, 0xb5, 0x1f, 0xb4, 0x92, 0x9b, 0x5e, 0xdd, 0x6b, 0x14, 0x5b, 0x45, 0xac, 0x5c, 0x68, 0x25,
	0x69, 0x08, 0x6b, 0x38, 0x78, 0x26, 0x70, 0xce, 0xed, 0x23, 0x3e, 0x14, 0x2c, 0xa6, 0x1d, 0x77,
	0xdc, 0x48, 0xde, 0x1e, 0xcf, 0x3b, 0xb4, 0x09, 0xa5, 0x69, 0xbc, 0xa3, 0xa9, 0x00, 0x2e, 0x9d,
	0x64, 0x59, 0xb1, 0x05, 0x47, 0x92, 0xaa, 0x3b, 0x89, 0x84, 0x9c, 0xd2, 0x4d, 0x4a, 0x90, 0xe3,
	0xb6, 0xe8, 0x46, 0xd2, 0x03, 0x3d, 0x06, 0x3f, 0x83, 0x5f, 0xe8, 0x3a, 0x87, 0x1f, 0xcb, 0x90,
	0xc3, 0x51, 0xf2, 0xe2, 0x41, 0xf1, 0xc7, 0x0d, 0xd2, 0x08, 0x33, 0x01, 0x84, 0x33, 0x9d, 0x0c,
	0xf6, 0x17, 0x40, 0xa6, 0x5a, 0xe8, 0xf6, 0xeb, 0xe7, 0xd7, 0xfb, 0x52, 0x99, 0xf8, 0x2c, 0x1b,
	0x7e, 0x37, 0xd6, 0x86, 0x3c, 0x7b, 0x50, 0x70, 0x46, 0x91, 0xdd, 0x79, 0x7b, 0xa7, 0x9d, 0x0f,
	0xf6, 0xfe, 0xc5, 0x39, 0xf6, 0x1d, 0x64, 0xdf, 0x22, 0xd5, 0x19, 0xec, 0x23, 0x17, 0xde, 0x98,
	0xbc, 0x79, 0x00, 0xbf, 0x36, 0x92, 0xb9, 0xb7, 0xcb, 0x44, 0x13, 0x1c, 0x2c, 0x02, 0x75, 0x5a,
	0x1a, 0xa8, 0x85, 0x92, 0xfa, 0x0c, 0x2d, 0x18, 0x29, 0x1b, 0xe1, 0x67, 0x7c, 0x5a, 0xb9, 0x29,
	0x4f, 0x42, 0x9e, 0x1c, 0xc8, 0x0c, 0x13, 0xa1, 0x6f, 0xf3, 0xf8, 0xca, 0x9b, 0xdf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xe2, 0x9e, 0x18, 0x86, 0x4d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	ListTasks(ctx context.Context, in *QueryListTasksRequest, opts ...grpc.CallOption) (*QueryListTasksResponse, error)
	GetTask(ctx context.Context, in *QueryGetTaskRequest, opts ...grpc.CallOption) (*QueryGetTaskResponse, error)
	AgentTasks(ctx context.Context, in *QueryAgentTasksRequest, opts ...grpc.CallOption) (*QueryAgentTasksResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ListTasks(ctx context.Context, in *QueryListTasksRequest, opts ...grpc.CallOption) (*QueryListTasksResponse, error) {
	out := new(QueryListTasksResponse)
	err := c.cc.Invoke(ctx, "/portalchain.tasks.Query/ListTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetTask(ctx context.Context, in *QueryGetTaskRequest, opts ...grpc.CallOption) (*QueryGetTaskResponse, error) {
	out := new(QueryGetTaskResponse)
	err := c.cc.Invoke(ctx, "/portalchain.tasks.Query/GetTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AgentTasks(ctx context.Context, in *QueryAgentTasksRequest, opts ...grpc.CallOption) (*QueryAgentTasksResponse, error) {
	out := new(QueryAgentTasksResponse)
	err := c.cc.Invoke(ctx, "/portalchain.tasks.Query/AgentTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	ListTasks(context.Context, *QueryListTasksRequest) (*QueryListTasksResponse, error)
	GetTask(context.Context, *QueryGetTaskRequest) (*QueryGetTaskResponse, error)
	AgentTasks(context.Context, *QueryAgentTasksRequest) (*QueryAgentTasksResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) ListTasks(ctx context.Context, req *QueryListTasksRequest) (*QueryListTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (*UnimplementedQueryServer) GetTask(ctx context.Context, req *QueryGetTaskRequest) (*QueryGetTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (*UnimplementedQueryServer) AgentTasks(ctx context.Context, req *QueryAgentTasksRequest) (*QueryAgentTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AgentTasks not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portalchain.tasks.Query/ListTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListTasks(ctx, req.(*QueryListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portalchain.tasks.Query/GetTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetTask(ctx, req.(*QueryGetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AgentTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAgentTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AgentTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portalchain.tasks.Query/AgentTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AgentTasks(ctx, req.(*QueryAgentTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "portalchain.tasks.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTasks",
			Handler:    _Query_ListTasks_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _Query_GetTask_Handler,
		},
		{
			MethodName: "AgentTasks",
			Handler:    _Query_AgentTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portalchain/tasks/query.proto",
}
