// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: portalchain/tasks/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateTask struct {
	Creator              string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	QueryHash            string   `protobuf:"bytes,2,opt,name=query_hash,json=queryHash,proto3" json:"query_hash,omitempty"`
	QueryUrl             string   `protobuf:"bytes,3,opt,name=query_url,json=queryUrl,proto3" json:"query_url,omitempty"`
	TaskType             string   `protobuf:"bytes,4,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCreateTask) Reset()         { *m = MsgCreateTask{} }
func (m *MsgCreateTask) String() string { return proto.CompactTextString(m) }
func (*MsgCreateTask) ProtoMessage()    {}
func (*MsgCreateTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_71a543d40b0f16ff, []int{0}
}
func (m *MsgCreateTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateTask.Unmarshal(m, b)
}
func (m *MsgCreateTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateTask.Marshal(b, m, deterministic)
}
func (m *MsgCreateTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateTask.Merge(m, src)
}
func (m *MsgCreateTask) XXX_Size() int {
	return xxx_messageInfo_MsgCreateTask.Size(m)
}
func (m *MsgCreateTask) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateTask.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateTask proto.InternalMessageInfo

func (m *MsgCreateTask) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateTask) GetQueryHash() string {
	if m != nil {
		return m.QueryHash
	}
	return ""
}

func (m *MsgCreateTask) GetQueryUrl() string {
	if m != nil {
		return m.QueryUrl
	}
	return ""
}

func (m *MsgCreateTask) GetTaskType() string {
	if m != nil {
		return m.TaskType
	}
	return ""
}

type MsgCreateTaskResponse struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Agent                string   `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCreateTaskResponse) Reset()         { *m = MsgCreateTaskResponse{} }
func (m *MsgCreateTaskResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateTaskResponse) ProtoMessage()    {}
func (*MsgCreateTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_71a543d40b0f16ff, []int{1}
}
func (m *MsgCreateTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateTaskResponse.Unmarshal(m, b)
}
func (m *MsgCreateTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateTaskResponse.Marshal(b, m, deterministic)
}
func (m *MsgCreateTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateTaskResponse.Merge(m, src)
}
func (m *MsgCreateTaskResponse) XXX_Size() int {
	return xxx_messageInfo_MsgCreateTaskResponse.Size(m)
}
func (m *MsgCreateTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateTaskResponse proto.InternalMessageInfo

func (m *MsgCreateTaskResponse) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *MsgCreateTaskResponse) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

type MsgSubmitResult struct {
	Agent                string   `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	TaskId               string   `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ResultHash           string   `protobuf:"bytes,3,opt,name=result_hash,json=resultHash,proto3" json:"result_hash,omitempty"`
	ResultUrl            string   `protobuf:"bytes,4,opt,name=result_url,json=resultUrl,proto3" json:"result_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgSubmitResult) Reset()         { *m = MsgSubmitResult{} }
func (m *MsgSubmitResult) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitResult) ProtoMessage()    {}
func (*MsgSubmitResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_71a543d40b0f16ff, []int{2}
}
func (m *MsgSubmitResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSubmitResult.Unmarshal(m, b)
}
func (m *MsgSubmitResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSubmitResult.Marshal(b, m, deterministic)
}
func (m *MsgSubmitResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitResult.Merge(m, src)
}
func (m *MsgSubmitResult) XXX_Size() int {
	return xxx_messageInfo_MsgSubmitResult.Size(m)
}
func (m *MsgSubmitResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitResult.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitResult proto.InternalMessageInfo

func (m *MsgSubmitResult) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

func (m *MsgSubmitResult) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *MsgSubmitResult) GetResultHash() string {
	if m != nil {
		return m.ResultHash
	}
	return ""
}

func (m *MsgSubmitResult) GetResultUrl() string {
	if m != nil {
		return m.ResultUrl
	}
	return ""
}

type MsgSubmitResultResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgSubmitResultResponse) Reset()         { *m = MsgSubmitResultResponse{} }
func (m *MsgSubmitResultResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitResultResponse) ProtoMessage()    {}
func (*MsgSubmitResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_71a543d40b0f16ff, []int{3}
}
func (m *MsgSubmitResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSubmitResultResponse.Unmarshal(m, b)
}
func (m *MsgSubmitResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSubmitResultResponse.Marshal(b, m, deterministic)
}
func (m *MsgSubmitResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitResultResponse.Merge(m, src)
}
func (m *MsgSubmitResultResponse) XXX_Size() int {
	return xxx_messageInfo_MsgSubmitResultResponse.Size(m)
}
func (m *MsgSubmitResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitResultResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateTask)(nil), "portalchain.tasks.MsgCreateTask")
	proto.RegisterType((*MsgCreateTaskResponse)(nil), "portalchain.tasks.MsgCreateTaskResponse")
	proto.RegisterType((*MsgSubmitResult)(nil), "portalchain.tasks.MsgSubmitResult")
	proto.RegisterType((*MsgSubmitResultResponse)(nil), "portalchain.tasks.MsgSubmitResultResponse")
}

func init() { proto.RegisterFile("portalchain/tasks/tx.proto", fileDescriptor_71a543d40b0f16ff) }

var fileDescriptor_71a543d40b0f16ff = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x66, 0x5b, 0x6d, 0xed, 0xa8, 0x88, 0x8b, 0xd2, 0xb4, 0xa5, 0x58, 0x72, 0x2a, 0x1e, 0x52,
	0xd0, 0x37, 0x50, 0x10, 0x3d, 0xf4, 0x52, 0x5b, 0x10, 0x0f, 0x86, 0x6d, 0xbb, 0x24, 0xa1, 0x31,
	0x59, 0x77, 0x36, 0xd0, 0xdc, 0xc4, 0x17, 0xf3, 0xd5, 0x24, 0xbb, 0x89, 0x6e, 0x54, 0xe8, 0xf1,
	0xfb, 0x99, 0xd9, 0xf9, 0x66, 0x07, 0xfa, 0x22, 0x95, 0x8a, 0xc5, 0xab, 0x90, 0x45, 0xc9, 0x44,
	0x31, 0xdc, 0xe0, 0x44, 0x6d, 0x3d, 0x21, 0x53, 0x95, 0xd2, 0x53, 0x4b, 0xf3, 0xb4, 0xe6, 0x7e,
	0x10, 0x38, 0x9e, 0x62, 0x70, 0x2b, 0x39, 0x53, 0x7c, 0xce, 0x70, 0x43, 0x1d, 0x68, 0xaf, 0x0a,
	0x94, 0x4a, 0x87, 0x8c, 0xc8, 0xb8, 0x33, 0xab, 0x20, 0x1d, 0x02, 0xbc, 0x65, 0x5c, 0xe6, 0x7e,
	0xc8, 0x30, 0x74, 0x1a, 0x5a, 0xec, 0x68, 0xe6, 0x9e, 0x61, 0x48, 0x07, 0x60, 0x80, 0x9f, 0xc9,
	0xd8, 0x69, 0x6a, 0xf5, 0x40, 0x13, 0x0b, 0x19, 0x17, 0x62, 0xf1, 0xa0, 0xaf, 0x72, 0xc1, 0x9d,
	0x3d, 0x23, 0x16, 0xc4, 0x3c, 0x17, 0xdc, 0xbd, 0x83, 0xf3, 0xda, 0x0c, 0x33, 0x8e, 0x22, 0x4d,
	0x90, 0xd3, 0x2e, 0xb4, 0x75, 0x55, 0xb4, 0x2e, 0x67, 0x69, 0x15, 0xf0, 0x61, 0x4d, 0xcf, 0x60,
	0x9f, 0x05, 0x3c, 0x51, 0xe5, 0x14, 0x06, 0xb8, 0xef, 0x04, 0x4e, 0xa6, 0x18, 0x3c, 0x66, 0xcb,
	0xd7, 0x48, 0xcd, 0x38, 0x66, 0xb1, 0xfa, 0x71, 0x12, 0xcb, 0x69, 0x37, 0x6e, 0xd4, 0x1a, 0x5f,
	0xc0, 0xa1, 0xd4, 0x85, 0x26, 0xa4, 0x89, 0x01, 0x86, 0xd2, 0x29, 0x87, 0x50, 0x22, 0x1d, 0xd3,
	0x24, 0xe9, 0x18, 0x66, 0x21, 0x63, 0xb7, 0x07, 0xdd, 0x5f, 0x13, 0x54, 0x61, 0xae, 0x3e, 0x09,
	0x34, 0xa7, 0x18, 0xd0, 0x27, 0x00, 0x6b, 0xdd, 0x23, 0xef, 0xcf, 0xa7, 0x78, 0xb5, 0x65, 0xf4,
	0xc7, 0xbb, 0x1c, 0xdf, 0xeb, 0x7a, 0x81, 0xa3, 0x5a, 0x76, 0xf7, 0xff, 0x4a, 0xdb, 0xd3, 0xbf,
	0xdc, 0xed, 0xa9, 0xfa, 0xdf, 0x0c, 0x9e, 0x7b, 0xf6, 0x75, 0x6d, 0xab, 0xfb, 0xca, 0x05, 0xc7,
	0x65, 0x4b, 0xdf, 0xd8, 0xf5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x39, 0xe5, 0xcc, 0x3e, 0x81,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateTask(context.Context, *MsgCreateTask) (*MsgCreateTaskResponse, error)
	SubmitResult(context.Context, *MsgSubmitResult) (*MsgSubmitResultResponse, error)
}

// RegisterMsgServer registers the MsgServer to the gRPC server.
func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "portalchain.tasks.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _Msg_CreateTask_Handler,
		},
		{
			MethodName: "SubmitResult",
			Handler:    _Msg_SubmitResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portalchain/tasks/tx.proto",
}

func _Msg_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portalchain.tasks.Msg/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateTask(ctx, req.(*MsgCreateTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portalchain.tasks.Msg/SubmitResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitResult(ctx, req.(*MsgSubmitResult))
	}
	return interceptor(ctx, in, info, handler)
}
